version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wp-company
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress-data:/var/www/html
      - ./company-theme:/var/www/html/wp-content/themes/company-theme
      - ./company-features:/var/www/html/wp-content/plugins/company-features
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: wp-company-db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db_data: